"""Guided setup of filtered StubHub views, one per tier.

StubHub shows ~10 listings per page load and refused "show more" in testing, so the tracker
loads one filtered page per tier instead. The filter is set by a person, in the tool's own
Chrome window: click the tier's sections on the map, sort by lowest price, press Enter. The
tool then records the page's URL, checks the filter really worked (URL changed, listed
sections belong to the tier, prices ascending), and writes config/stubhub_views.toml.

Nothing is written for a tier whose check fails, and the reason is printed.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import parse_qsl, urlsplit

from ticket.config import CONFIG_DIR, TIERS, load_section_tiers, tier_for

VIEWS_FILE = CONFIG_DIR / "stubhub_views.toml"


@dataclass
class ViewCheck:
    tier: str
    url: str
    changed_params: dict[str, str]
    sections_seen: list[str]
    out_of_tier: list[str]
    prices: list[float]
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems


def query_diff(base_url: str, new_url: str) -> dict[str, str]:
    """Query parameters that were added or changed (quantity excluded)."""
    base = dict(parse_qsl(urlsplit(base_url).query))
    new = dict(parse_qsl(urlsplit(new_url).query))
    return {k: v for k, v in new.items() if base.get(k) != v and k.lower() != "quantity"}


def check_view(tier: str, base_url: str, url: str, cards: list[dict], tiers: dict[str, str]) -> ViewCheck:
    from ticket.stubhub.dom import extract_cards

    changed = query_diff(base_url, url)
    res = extract_cards(cards, 2, url)
    sections = [l.section or "?" for l in res.listings]
    out = sorted({s for s in sections if tier_for(s, tiers) != tier})
    prices = [l.price_per_ticket for l in res.listings if l.price_per_ticket is not None]
    chk = ViewCheck(tier, url, changed, sections, out, prices)
    if not changed:
        chk.problems.append("the URL did not change, so this filter can't be saved as a link. "
                            "StubHub may keep the section filter inside the page only")
    if not res.listings:
        chk.problems.append("no listings on the filtered page: either nothing is for sale in these "
                            "sections right now, or the filter didn't apply")
    if out:
        chk.problems.append(f"listings from sections outside the {tier!r} tier: {out}")
    if prices != sorted(prices):
        chk.problems.append(f"prices are not lowest-first: {prices}")
    return chk


def write_views(checks: list[ViewCheck], path: Path = VIEWS_FILE) -> None:
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [f"# Generated by `python -m ticket stubhub setup-views` on {stamp}.",
             "# Each URL was checked: only that tier's sections listed, lowest price first.",
             "# Safe to edit or delete; re-run setup-views to regenerate.", ""]
    for c in checks:
        lines += ["[[views]]", f"name = {json.dumps(c.tier)}", f"url = {json.dumps(c.url)}",
                  f"# check: {len(c.sections_seen)} listings, sections {sorted(set(c.sections_seen))}, "
                  f"URL params {c.changed_params}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def tier_sections(path: Path | None = None) -> dict[str, list[str]]:
    import tomllib
    with (path or CONFIG_DIR / "sections.toml").open("rb") as f:
        raw = tomllib.load(f)
    return {t: list(raw.get("tiers", {}).get(t, [])) for t in TIERS}


def run_wizard(sources, only: list[str] | None = None) -> int:
    from playwright.sync_api import TimeoutError as PWTimeout
    from playwright.sync_api import sync_playwright

    from ticket.stubhub.dom import CARDS_JS
    from ticket.stubhub.fetch import _check_block, launch_context, with_quantity

    cfg = sources.stubhub
    tiers = load_section_tiers()
    wanted = tier_sections()
    base = with_quantity(cfg.event_url, cfg.quantity)
    good: list[ViewCheck] = []
    failed: list[ViewCheck] = []

    with sync_playwright() as p:
        ctx = launch_context(p, cfg, headless=False)   # a person has to see and click it
        try:
            page = ctx.new_page()
            for tier in TIERS:
                if only and tier not in only:
                    continue
                page.goto(base, wait_until="domcontentloaded", timeout=60_000)
                try:
                    page.wait_for_load_state("networkidle", timeout=15_000)
                except PWTimeout:
                    pass
                _, block = _check_block(page, None)
                if block:
                    print(f"\nStubHub is showing a check ({block}). Solve it in the Chrome window, "
                          "then press Enter.")
                    input()
                print(f"\n=== Tier {tier!r} ===")
                print("In the Chrome window:")
                print(f"  1. Click these sections on the seat map (and only these): {', '.join(wanted[tier])}")
                print("  2. Set the sort to lowest price first.")
                print("  3. Wait until the listings update, then press Enter here.")
                print("     (Type 'skip' and Enter to skip this tier.)")
                if input().strip().lower() == "skip":
                    continue
                try:
                    page.wait_for_load_state("networkidle", timeout=10_000)
                except PWTimeout:
                    pass
                chk = check_view(tier, base, page.url, page.evaluate(CARDS_JS), tiers)
                print(f"  URL now: {chk.url}")
                print(f"  changed URL settings: {chk.changed_params or 'NONE'}")
                print(f"  listings shown: {len(chk.sections_seen)} in sections {sorted(set(chk.sections_seen))}")
                print(f"  prices: {chk.prices}")
                if chk.ok:
                    print("  OK: this view will be saved.")
                    good.append(chk)
                else:
                    for prob in chk.problems:
                        print(f"  !! {prob}")
                    print("  NOT saved.")
                    failed.append(chk)
        finally:
            ctx.close()

    if good:
        # Keep previously saved tiers that weren't redone this time.
        keep = [v for v in _existing_views() if v[0] not in {c.tier for c in good}]
        merged = [ViewCheck(n, u, {}, [], [], []) for n, u in keep] + good
        write_views(merged)
        print(f"\nSaved {len(good)} view(s) to {VIEWS_FILE}: {[c.tier for c in good]}")
    if failed:
        print(f"\n!! {len(failed)} tier(s) failed the check: {[c.tier for c in failed]}. "
              "Paste this output to Claude.")
        return 2
    return 0 if good else 1


def _existing_views() -> list[tuple[str, str]]:
    import tomllib
    if not VIEWS_FILE.exists():
        return []
    with VIEWS_FILE.open("rb") as f:
        return [(v["name"], v["url"]) for v in tomllib.load(f).get("views", [])]
